services:
  health-facilities-tracker-db:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_TEST:-root_password}
      MYSQL_USER: ${DB_USER_TEST:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD_TEST:-user_password}
      MYSQL_DATABASE: ${DB_NAME_TEST:-health-facilities-tracker_db}

    ports:
      - ${DB_PORT_TEST:-3307}:3306

    volumes:
      - health-facilities-tracker-db-test-data:/var/lib/mysql

volumes:
  health-facilities-tracker-db-test-data:
