"""add_unique_constraint_to_facilities

Revision ID: 44ac8265a1eb
Revises: f24402834ffe
Create Date: 2025-10-20 00:48:00.741285

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44ac8265a1eb"
down_revision: Union[str, Sequence[str], None] = "f24402834ffe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unq_sub_district_facility", "facilities", ["sub_district_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unq_sub_district_facility", "facilities", type_="unique")
    # ### end Alembic commands ###
