"""create_unique_constraints_districts_sub_districts

Revision ID: 5e5c265e9ef2
Revises: 9c0fe9531631
Create Date: 2025-10-20 02:10:13.893711

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e5c265e9ef2"
down_revision: Union[str, Sequence[str], None] = "9c0fe9531631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unq_region_district", "districts", ["region_id", "name"])
    op.create_unique_constraint("unq_sub_district_district", "sub_districts", ["district_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unq_sub_district_district", "sub_districts", type_="unique")
    op.drop_constraint("unq_region_district", "districts", type_="unique")
    # ### end Alembic commands ###
