# """change_is_liscensed_to_is_licensed_in_facilities

# Revision ID: 661f8ea08698
# Revises: c64f41994df4
# Create Date: 2026-04-13 16:56:24.252375

# """

# from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision: str = "661f8ea08698"
# down_revision: Union[str, Sequence[str], None] = "c64f41994df4"
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column("facilities", sa.Column("is_licensed", sa.Boolean(), nullable=True))
#     op.drop_column("facilities", "is_liscensed")
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "facilities", sa.Column("is_liscensed", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)
#     )
#     op.drop_column("facilities", "is_licensed")
#     # ### end Alembic commands ###


"""change_is_liscensed_to_is_licensed_in_facilities

Revision ID: 661f8ea08698
Revises: c64f41994df4
Create Date: 2026-04-13 16:56:24.252375
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "661f8ea08698"
down_revision: Union[str, Sequence[str], None] = "c64f41994df4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE_NAME = "facilities"


def get_columns() -> list:
    """Helper to safely fetch existing columns in table."""
    conn = op.get_bind()
    inspector = inspect(conn)
    return [col["name"] for col in inspector.get_columns(TABLE_NAME)]


def upgrade() -> None:
    """Upgrade schema safely (idempotent)."""
    columns = get_columns()

    # Add correct column if missing
    if "is_licensed" not in columns:
        op.add_column(
            TABLE_NAME,
            sa.Column("is_licensed", sa.Boolean(), nullable=True),
        )

    # Remove old misspelled column if it exists
    if "is_liscensed" in columns:
        op.drop_column(TABLE_NAME, "is_liscensed")


def downgrade() -> None:
    """Downgrade schema safely (idempotent)."""
    columns = get_columns()

    # Restore old column if missing
    if "is_liscensed" not in columns:
        op.add_column(
            TABLE_NAME,
            sa.Column("is_liscensed", sa.Boolean(), nullable=True),
        )

    # Remove new column if it exists
    if "is_licensed" in columns:
        op.drop_column(TABLE_NAME, "is_licensed")
