"""update_altitude_range

Revision ID: 9c0fe9531631
Revises: 44ac8265a1eb
Create Date: 2025-10-20 01:51:34.750605

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9c0fe9531631"
down_revision: Union[str, Sequence[str], None] = "44ac8265a1eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facilities",
        "altitude",
        existing_type=mysql.DECIMAL(precision=12, scale=9),
        type_=sa.Numeric(precision=14, scale=9),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facilities",
        "altitude",
        existing_type=sa.Numeric(precision=14, scale=9),
        type_=mysql.DECIMAL(precision=12, scale=9),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
